-- ASCEND — GROUNDED EDUCATION ENGINE V1 SEED (part 1/3): educational_resources (1-12)
insert into public.educational_resources
  (title, source, url, license, description, subject_domain, difficulty, learning_purpose, provenance)
values
  ('MIT OCW — Classical Mechanics', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/physics/8-01sc-classical-mechanics-fall-2016/', 'CC BY-NC-SA 4.0', 'Full course: kinematics, Newton''s laws, energy, momentum, rotation.', 'Engineering Physics', 'intermediate', 'Conceptual foundation + worked examples', 'Massachusetts Institute of Technology'),
  ('MIT OCW — Electricity and Magnetism', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/physics/8-02sc-physics-ii-electricity-and-magnetism-fall-2010/', 'CC BY-NC-SA 4.0', 'Fields, circuits, Maxwell''s equations with lecture notes.', 'Engineering Physics', 'intermediate', 'Academic explanation + problem solving', 'Massachusetts Institute of Technology'),
  ('MIT OCW — Single Variable Calculus', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/', 'CC BY-NC-SA 4.0', 'Limits, derivatives, integrals, fundamental theorem.', 'Mathematics', 'intermediate', 'Why/how + worked examples', 'Massachusetts Institute of Technology'),
  ('MIT OCW — Linear Algebra (Strang)', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/', 'CC BY-NC-SA 4.0', 'Vectors, matrices, eigenvalues, applications.', 'Mathematics', 'advanced', 'Theory + real-world applications', 'Massachusetts Institute of Technology'),
  ('MIT OCW — Introduction to Computer Science (6.0001)', 'MIT OpenCourseWare', 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/', 'CC BY-NC-SA 4.0', 'Python-based intro to computation and problem solving.', 'Computer Science', 'beginner', 'Programming fundamentals', 'Massachusetts Institute of Technology'),
  ('Khan Academy — Physics', 'Khan Academy', 'https://www.khanacademy.org/science/physics', 'CC BY-NC-SA 3.0', 'Short lessons on motion, forces, waves, optics.', 'Engineering Physics', 'beginner', 'Simple explanation + intuition', 'Khan Academy'),
  ('Khan Academy — Mathematics', 'Khan Academy', 'https://www.khanacademy.org/math', 'CC BY-NC-SA 3.0', 'Arithmetic through calculus with practice.', 'Mathematics', 'beginner', 'Simple explanation + practice', 'Khan Academy'),
  ('Khan Academy — Computing', 'Khan Academy', 'https://www.khanacademy.org/computing', 'CC BY-NC-SA 3.0', 'Programming, algorithms, and computer science basics.', 'Computer Science', 'beginner', 'Programming fundamentals', 'Khan Academy'),
  ('NPTEL — Programming in C', 'NPTEL', 'https://nptel.ac.in/courses', 'Free for educational use (© IIT/NPTEL)', 'IIT lecture series on C programming.', 'C', 'beginner', 'Academic explanation + examples', 'NPTEL, Indian Institutes of Technology'),
  ('NPTEL — Python for Data Science', 'NPTEL', 'https://nptel.ac.in/courses', 'Free for educational use (© IIT/NPTEL)', 'Python foundations for data science.', 'Python', 'beginner', 'Programming fundamentals', 'NPTEL, Indian Institutes of Technology'),
  ('NPTEL — Engineering Physics', 'NPTEL', 'https://nptel.ac.in/courses', 'Free for educational use (© IIT/NPTEL)', 'Core engineering physics lectures.', 'Engineering Physics', 'intermediate', 'Academic explanation', 'NPTEL, Indian Institutes of Technology'),
  ('Python Official Documentation', 'Python Software Foundation', 'https://docs.python.org/3/', 'Python Software Foundation License v2', 'Authoritative language reference and tutorial.', 'Python', 'beginner', 'Reference / official documentation', 'Python Software Foundation');
