// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// ROOT-CAUSE FIX: previously we attached `getSession().access_token` verbatim.
// That token can be EXPIRED (e.g. after the tab was idle or right after a page
// refresh before the Supabase client auto-refreshed). Sending an expired token
// made the server's `requireSupabaseAuth` middleware reject it with
// "Unauthorized: Invalid token" — the exact CSE Tutor failure reported.
//
// Fix: proactively refresh the session when it is missing, expired, or within
// 60s of expiry, and attach the fresh token. This is the single, consistent
// authenticated architecture used by every server function.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let token = data.session?.access_token;
    const expiresAt = data.session?.expires_at; // unix seconds
    const nearExpiry = expiresAt ? Date.now() / 1000 >= expiresAt - 60 : false;

    if ((!token || nearExpiry) && data.session) {
      const { data: refreshed } = await supabase.auth.refreshSession();
      token = refreshed.session?.access_token ?? token;
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
