// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import {
  ensureOwnerSession,
  getOwnerAccessTokenSync,
  isOwnerSessionBootstrapping,
} from "@/lib/owner-session";

// Must be registered as a global `functionMiddleware` in `src/start.ts`;
// otherwise the browser never attaches the bearer token to serverFn RPCs.
//
// Single-owner note: this used to read `getSession()` and self-refresh an
// expired token. There is no browser session any more — the owner access token
// is held in memory and minted server-side — so this now just attaches the
// current token, and asks the owner-session endpoint for one only if we do not
// already have a fresh bootstrap in flight (that guard prevents recursion,
// because this middleware also runs for the owner-session call itself).
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token = getOwnerAccessTokenSync();

    if (!token && !isOwnerSessionBootstrapping()) {
      try {
        await ensureOwnerSession();
        token = getOwnerAccessTokenSync();
      } catch {
        // Fail closed: send no Authorization header. The server rejects the
        // call rather than granting unauthenticated access.
        token = null;
      }
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
