// This file is automatically generated. Do not edit it directly.
//
// Single-owner browser client.
//
// Session model: there is no browser-side login. The app obtains a legitimate
// Supabase access token for the existing owner from the private owner-session
// endpoint (server-only refresh token) and keeps it in memory only. Requests
// then carry `Authorization: Bearer <access token>`, which is exactly what
// Supabase RLS (`auth.uid()`) and the server-side `requireSupabaseAuth`
// already expect — so every existing policy keeps working unchanged.
//
// `persistSession`/`autoRefreshToken` are off on purpose: the refresh token
// must never reach the browser, so the browser cannot refresh on its own. On a
// 401 it asks the owner-session endpoint for a fresh access token instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  ensureOwnerSession,
  getOwnerAccessTokenSync,
  isOwnerSessionFresh,
} from "@/lib/owner-session";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  // ONE forced owner-session refresh per wave. Without this, every concurrent
  // 401 that landed *after* the previous refresh resolved started its own
  // forced bootstrap (`force` skips the freshness check), so a burst of parallel
  // queries produced a 401 -> refresh -> 401 storm.
  let refreshWave: Promise<unknown> | null = null;

  const refreshOnce = (): Promise<unknown> => {
    if (!refreshWave) {
      const wave = ensureOwnerSession(true).catch(() => undefined);
      refreshWave = wave;
      // Release the slot once this wave settles, so a later, genuinely separate
      // 401 can start a new one.
      void wave.then(() => {
        if (refreshWave === wave) refreshWave = null;
      });
    }
    return refreshWave;
  };

  return async (input, init) => {
    const send = async (): Promise<Response> => {
      const headers = new Headers(
        typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
      );

      if (init?.headers) {
        new Headers(init.headers).forEach((value, key) => headers.set(key, value));
      }

      // New Supabase API keys are opaque strings, not bearer JWTs.
      if (
        isNewSupabaseApiKey(supabaseKey) &&
        headers.get("Authorization") === `Bearer ${supabaseKey}`
      ) {
        headers.delete("Authorization");
      }

      const token = getOwnerAccessTokenSync();
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      headers.set("apikey", supabaseKey);

      return fetch(input, { ...init, headers });
    };

    let response = await send();

    // Exactly one retry per original request. Requests that 401 while a refresh
    // is in flight await that same promise; if the retry 401s again it is
    // surfaced as-is and must NOT trigger a second refresh.
    if (response.status === 401) {
      await refreshOnce();
      response = await send();
    }

    return response;
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

export { isOwnerSessionFresh };

// Exported so the 401 single-flight behaviour is directly regression-testable.
export { createSupabaseFetch };
